#!/usr/bin/env bash

Execution () {
a='1024'
LANG='en_US'
LANGUAGE='en_US'
type='ed25519'
comment="`echo ${type} | tr [a-z] [A-Z]` `date +"%d-%b-%Y %H:%M:%S %Z"` `uname -n`"
echo ${comment}
ssh-keygen -o -t ${type} -a ${a} -C "$comment"
}

Execution;
unset Execution;